version: '3.7'
services:
  api:
    build: .
    volumes:
      - .:/usr/src/mini-wallet
    ports:
      - 3000:3000 # API server
    depends_on:
      - postgres
    restart: always
    networks:
      - miniwallet


  postgres:
    image: postgres
    container_name: mini-wallet-db
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mini_wallets
    networks:
      - miniwallet
volumes:
  pg_data:

networks:
  miniwallet:
    driver: bridge